/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f8fafc",
        "surface-dim": "#e2e8f0",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f5f9",
        "surface-container": "#f1f5f9",
        "surface-container-high": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        "inverse-surface": "#1e293b",
        "inverse-on-surface": "#f8fafc",
        outline: "#94a3b8",
        "outline-variant": "#e2e8f0",
        "surface-tint": "#0284c7",
        primary: "#0284c7",
        "primary-container": "#0284c7",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "primary-fixed": "#cce5ff",
        "primary-fixed-dim": "#93ccff",
        "on-primary-fixed": "#001d31",
        "on-primary-fixed-variant": "#004b73",
        "inverse-primary": "#93ccff",
        secondary: "#0284c7",
        "secondary-container": "#e0f2fe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#0369a1",
        "secondary-fixed": "#b7eaff",
        "secondary-fixed-dim": "#6cd3f7",
        "on-secondary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#004e61",
        tertiary: "#059669",
        "tertiary-container": "#d1fae5",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#065f46",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        error: "#dc2626",
        "error-container": "#fee2e2",
        "on-error": "#ffffff",
        "on-error-container": "#991b1b",
        background: "#f8fafc",
        "on-background": "#0f172a",
        "surface-variant": "#f1f5f9",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.375rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      spacing: {
        "gutter-md": "1rem",
        gutter: "0.75rem",
        margin: "1rem",
        "margin-lg": "1.5rem",
        "space-2xs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        headline: ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        body: ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "data-mono-lg": ["JetBrains Mono", "monospace"],
        "data-mono-md": ["JetBrains Mono", "monospace"],
        "data-mono-sm": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["15px", { lineHeight: "22px", letterSpacing: "0", fontWeight: "600" }],
        "body-lg": ["15px", { lineHeight: "22px", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "18px", letterSpacing: "0", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "data-mono-lg": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "data-mono-md": ["13px", { lineHeight: "18px", letterSpacing: "0", fontWeight: "500" }],
        "data-mono-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "400" }],
        "label-caps": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
